services:
  - type: web
    name: crypto-trading-bot
    env: python
    region: singapore  # Closest to India
    plan: free  # Use Render's free tier
    buildCommand: pip install -r requirements.txt
    startCommand: python launch_web_dashboard.py
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: PORT
        value: 8000
    healthCheckPath: /health
